MathLebl/Resistenfance

- app/controllers/audio_messages_controller.rb
- app/controllers/users/confirmations_controller.rb
- app/controllers/users/omniauth_callbacks_controller.rb
- app/controllers/users/passwords_controller.rb
- app/controllers/users/registrations_controller.rb
- app/controllers/users/sessions_controller.rb
- app/controllers/users/unlocks_controller.rb
- app/models/audio_message.rb
- app/views/audio_messages/destroy.html.erb
- app/views/audio_messages/index.html.erb
- app/views/audio_messages/new.html.erb
- app/views/audio_messages/show.html.erb
- config/routes.rb
- db/migrate/20200415110915_create_audio_messages.rb
- db/migrate/20200415112056_create_active_storage_tables.active_storage.rb
- db/migrate/20200415113447_add_description_to_audio_message.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/audio_messages_controller_test.rb
- test/models/audio_message_test.rb
- Création de la base de donnée (uniquement les messages audio et la relation avec les users pour l'instant)
- new/create/show pour audio message ok !
- Implémentation d'une fonction pour réécouter le message sur la page show d'un message audio
> Created database

- Gemfile
- app/javascript/channels/index.js
- app/javascript/channels/sound_recorder.js
- app/views/audio_messages/new.html.erb
- app/views/shared/_navbar.html.erb
J'ai créé un fichier js pour enregistre un message vocal directement sur le site web
il est pas encore terminé mais c'est pour montrer
> proto en js du recording directement sur site web

- app/controllers/pages_controller.rb
- app/services/message_crypter.rb
- app/views/pages/home.html.erb
- Ajout d'un dossier "services" pour simplifier l'appel de la fonction message crypter
- Ajout d'une classe **"MessageCrypter"** qui à la possibilité de crypter / décrypter un message
_Il suffit de créer une instance de **MessageCrypter** avec comme seul argument le message à crypter, puis d'appeler la méthode d'instance "encrypt"_ (voir pages_controller) _pour récupérer le message crypté_
note : Par défaut j'ai mis un décalage de 2 lettres vers l'arrière, on peut aussi passer à une seule lettre vers l'avant ça sera moins compliqué pour les enfants (plus intuitif) ! 
La fonction décryptage est facultative étant donné qu'on a déjà les messages originaux en DB, c'était plus pour vérifier le bon fonctionnement de la méthode 😉 
- Ajout d'un exemple dans view/home.html.erb pour illustrer la …
> Message crypter

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_background.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- Ajout de la vidéo du générale Zoé
- Modification de la Navbar > ajout du logo
- fix de la position des éléments d'arrière plan
- Ajout des liens de connexion et vers l'index des messages
- Ajout d'un hover de sélections sur les lien
-----------------
Le responsive n'est pas encore géré en fonction des devices mais les éléments conservent déjà un ratio correct d’espacement entre eux. 
> Rendu actuel sur 15"
> Design home

- app/controllers/application_controller.rb
- app/helpers/meta_tags_helper.rb
- app/views/layouts/application.html.erb
- config/initializers/default_meta.rb
- config/meta.yml
Files created
meta.yml
meta_tag_helper.rb
default_meta.rb
Modified
application_controller.rb
application.html.erb
> Og meta and favicon set

- app/assets/stylesheets/components/_grid.scss
- app/assets/stylesheets/components/_index.scss
- création d'un composant grid pour la répartitions des pages audios
> add a grid component for Amine

- app/channels/comment_channel.rb
- app/controllers/comments_controller.rb
- app/javascript/channels/comment_channel.js
- app/javascript/packs/application.js
- app/javascript/packs/message_creator.js
- app/views/audio_messages/index.html.erb
- app/views/comments/_comment.html.erb
- test/channels/comment_channel_test.rb
_Sorry, c'est un commit pour tout en même temps, j'espère que ça sera clair 🙏_
- **Nouveau Channel** : "comment_channel.rb" & "comment_channel.js pour action câble
- **Nouvelle partiale** : "_comment.html.erb** pour faciliter l'utilisation d'action câble et potentiellement réutiliser les commentaires ailleurs facilement.
Globalement peu de changements à part ce qu'il faut pour que le webSocket fonctionne !
Ajoute automatiquement les nouveaux commentaires postés, pour l'instant uniquement sur la page audio_messages index, si besoin on pourra faire pareil ailleurs sans souci !
> added action cable server, and implemented everything to make it work

- config/environments/production.rb
Bug fixed in Production.rb for mailer
> production smtp service

- config/routes.rb
J'ai changé la route pour le User#show
ça créait un conflit de path entre users/id et users/sign-in 
nouvelle route Users#show
/resistenfant/id
> routes bug fixed

- app/views/pages/home.html.erb
- config/initializers/devise.rb
Création d'un btn log out sur la home, pour le temps du développement.
initialiazer/devise modifié 
config.sign_out_via :get 
(nécessite un reboot du server)
> creation d'un log out provisoire

- config/environments/development.rb
- config/environments/production.rb
Modification de 
config/environments/production.rb
- GMAIL_USERNAME et GMAIL_PASSWORD en capital
config/environments/developement.rb
- GMAIL_USERNAME et GMAIL_PASSWORD en capital
> Authenticate Bug Fixed

- db/seeds.rb
Add **skip.confirmation** to the twousers create in the seeds
> skip confirmation for seed

- app/controllers/audio_messages_controller.rb
- app/controllers/pages_controller.rb
- app/views/comments/_comment.html.erb
- app/views/pages/home.html.erb
- Ajout de la fonction de cryptage des messages sur la view **audio messages index**
- Petites modifs sans grande importance
- J'ai aussi retiré la phrase message crypté sur la home page 👍
> added the crypted message to the audio message index view

- config/environments/production.rb
Toujours ma quette de faire fonctionner heeroku
> envi/production.rb modifié pour Asseys compilation

- config/environments/production.rb
- config/initializers/devise.rb
J'ai changé le mail par défaut en prod et le lien de confirmation en prod aussi.
> Confirmation Mailer fixed in prod

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_background.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_page.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/pages/home.html.erb
- app/views/shared/_background.html.erb
- Création d'un composant HTML pour l'arrière plan
- Ajouts de composants CSS pour l'arrière plan, la page et le formulaire des messages
- Nettoyage du CSS
- Rectification de l'import des pages CSS
------------
Bien que le responsive ne soit pas encore gérer, il suffit à présent d'import l'arrière plan avec un render. De même pour la page il suffit d'ajouter la classe `page` pour la mettre en forme.
> Exemple de mise en forme dans l'HTML
> Background component

- app/controllers/application_controller.rb
- app/controllers/confirmations_controller.rb
- config/initializers/devise.rb
- config/routes.rb
First Commit
*Sign In et Sign Up redirigent vers le user/show avec le sign_in ok*
**Application/controller.rb** modifié
*Delai d'un jour pour la confirmation par mail*
**initializers/devise.rb** modifié
Second Commit
*le link dans le mail de confirmation redirige vers le user/show avec le sign_in ok*
**routes.rb** modifié
**controllers/confirmations_controller** créé
> Redirections

- app/assets/stylesheets/components/_background.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_page.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/pages/home.html.erb
- app/views/shared/_background.html.erb
- Responsive des éléments de la home pour le devices supérieur à 1200px de large
- Remplacement du terme "quartier général" par "QG" pour des raison de gain de place et d'esthétique
Les éléments s'écartent du dossier quand on diminue la taille de la fenêtre, à voir si on règles ça dans dans la V2 mais je ne trouve pas ça particulièrement gênant pour l'instant, je le laisse donc comme ça pour l'instant.
> Responsive home

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_background.html.erb
- app/views/users/show.html.erb
Reverts MathLebl/Resistenfance#38
Bug avec le folder, je préfère enlevé plutot que de chier le bordel
> Revert "background in dedicated pages"

- app/assets/stylesheets/components/_background.scss
- app/assets/stylesheets/pages/_home.scss
> fix click on links

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/shared/_background.html.erb
- app/views/users/show.html.erb
Ajout du render Background dans les pages concernées
Ajout de la div class: page pour le layout
> Background renders

- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_page.scss
- app/assets/stylesheets/pages/_home.scss
- app/assets/stylesheets/pages/_user_show.scss
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/pages/home.html.erb
- app/views/users/show.html.erb
- Ajout d'un `page-container` sur les pages concernées
- Ajout d'une légère mise en forme sur ces même pages
------------
La mise en forme est temporaire il manque des choses et particulièrement sur le `sign-up` et le `user_show`. Le code n'est pas encore clean, j'ai juste fait en sorte que ce soit plus lisible sur le navigateur.
> fix render background

- app/assets/stylesheets/components/_form.scss
- app/controllers/comments_controller.rb
- app/javascript/channels/comment_channel.js
- app/javascript/packs/message_creator.js
- app/views/audio_messages/index.html.erb
-Pas grand chose à lister, les bugs qui étaient dû au fait que l'on ait plusieurs formulaires pour les commentaires des messages audio sont résolus, aussi bien dans rails qu'avec action câble.
_Note : je suis entrain de résoudre le conflit vu qu'une partiale à remplacé le code que j'ai touché, j'en ai pour 5 minutes_
> Comments forms bug

- app/views/shared/_audio_card.html.erb
Juste 2 ou 3 changements de noms de classes ou ID pour correspondre à ce que j'avais changé dans ma dernière PR.
En principe tout fonctionne maintenant en terme de post de commentaires
> Partial modif

- app/assets/stylesheets/pages/_index_audios.scss
- app/views/audio_messages/index.html.erb
- app/views/shared/_audio_card.html.erb
Le nom de branche ne correspond pas mais je voulais récupérer la dernière pull de Daj avant d'attaquer les commentaires.
Ici petit ajustement de div et de layout pour l'audio-message/index
> petit clean dans audio-messages/index
